/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // vert.x
    implementation("io.vertx:vertx-core:3.9.2")
    implementation("io.vertx:vertx-lang-kotlin:3.9.2")
    implementation("io.vertx:vertx-web:3.9.2")

    // lucene
    implementation("org.apache.lucene:lucene-core:8.6.1")
    implementation("org.apache.lucene:lucene-queryparser:8.6.1")
    implementation("org.apache.lucene:lucene-analyzers-common:8.6.1")

    // spek
    testImplementation("org.spekframework.spek2:spek-dsl-jvm:2.0.12")
    testRuntimeOnly("org.spekframework.spek2:spek-runner-junit5:2.0.12")
    testRuntimeOnly("org.jetbrains.kotlin:kotlin-reflect")

    // kluent
    testImplementation("org.amshove.kluent:kluent:1.61")

    // json serialization/deserialization of kotlin classes
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.10.3")
}

application {
    // Define the main class for the application.
    mainClassName = "wikicene.AppKt"
}

tasks {

    withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }

    // setup the test task
    test {
        useJUnitPlatform {
            includeEngines("spek2")
        }
    }
}
